name: Docker Image Action for ghcr.io

on:
  push:
    branches:
      - main

env:
  IMAGE: ${{ github.repository_owner }}/prom2-docker
  VERSION: v2.8.6hf

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Qemu
        uses: docker/setup-qemu-action@v3.0.0

      - name: Setup Buildx Environment
        uses: docker/setup-buildx-action@v3.3.0
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to the Github Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PASS }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push new Stable Image
        uses: docker/build-push-action@v5.3.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE }}:${{ env.VERSION }}
            ghcr.io/${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ env.VERSION }}
            ${{ env.IMAGE }}:latest
          cache-from: type=registry,ref=ghcr.io/${{ env.IMAGE }}:latest
          cache-to: type=inline
          provenance: false

      - name: Remove untagged images excepted multiplatform packages
        uses: Chizkiyahu/delete-untagged-ghcr-action@v4
        with:
          token: ${{ secrets.GH_PASS }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          untagged_only: true
          owner_type: user
          except_untagged_multiplatform: true
